server:
  port: 8085
debug: false
spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:appdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create